CREATE TABLE IF NOT EXISTS Banner 
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    UrlImage VARCHAR(500) NOT NULL,
    Url VARCHAR(300) NULL,
    StartDate DATETIME NULL,
    EndDate DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    Active TINYINT(1) NOT NULL DEFAULT 1,
    `Order` INT NULL
);  

CREATE TABLE IF NOT EXISTS Category 
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_Category_Name (Name)
);  

CREATE TABLE IF NOT EXISTS Contact 
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NULL,
    Message VARCHAR(500) NOT NULL,
    MessageDate DATETIME NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);  

CREATE TABLE IF NOT EXISTS Episode (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(250) NOT NULL,
    Description MEDIUMTEXT NOT NULL,
    ShortDescription VARCHAR(500) NOT NULL,
    Url VARCHAR(2000) NOT NULL,
    ImageUrl VARCHAR(2000) NOT NULL,
    PublishedAt DATETIME NOT NULL,
    Tags JSON NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    Active TINYINT(1) NOT NULL DEFAULT 1, 
    Number INT NOT NULL DEFAULT 0,
    CategoryId INT NOT NULL,
    DurationInSeconds INT NULL DEFAULT 0,
    `View` INT NOT NULL DEFAULT 0,
    `Like` INT NOT NULL DEFAULT 0,
    CreatedBy VARCHAR(50) NULL,
    UpdatedBy VARCHAR(50) NULL,
    CONSTRAINT FK_Episodes_Category FOREIGN KEY (CategoryId) REFERENCES Category(Id) ON UPDATE CASCADE ON DELETE RESTRICT,
    INDEX IDX_Episodes_PublishedAt (PublishedAt),
    INDEX IDX_Episodes_Active (Active),
    INDEX IDX_Episodes_Category (CategoryId),
    INDEX IDX_Episodes_Title (Title(191))
);

CREATE TABLE IF NOT EXISTS Team
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    UrlGitHub VARCHAR(500) NULL,
    UrlInstagram VARCHAR(500) NULL,
    UrlLinkedin VARCHAR(500) NULL,
    UrlImage VARCHAR(500) NOT NULL,
    Job VARCHAR(300) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
); 

CREATE TABLE IF NOT EXISTS UserAdmin
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    HashedPassword VARCHAR(500) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
); 

CREATE TABLE IF NOT EXISTS RefreshTokens 
(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    UserName VARCHAR(50) NULL,
    Token VARCHAR(255) NOT NULL,
    ExpirationDate DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES UserAdmin(Id)
); 


