#will be added in future migration
version: '3.8'
services: 
  mysql:
    container_name: breakingbaddb
    image: mysql:5.7
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: breakingbad-mysql-local
    ports:
      - "3308:3306"
